<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>TscFakePrinter</RootNamespace>
    <AssemblyName>TscFakePrinter</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="QRCoder" Version="1.4.3" />
    <PackageReference Include="ZXing.Net" Version="0.16.9" />
  </ItemGroup>

</Project>
